### ISSUE TITLE
HTML encoding when saving in Parameters editor dialog breaks SQL code

### ISSUE THREAD

**Issue by bittner** [xresch/EngineeredMonitoringPlatform#5] opened 2024-11-04 13:42 UTC
The <kbd>🎛 Params</kbd> editor dialog allows to edit an EMP-style SQL query (e.g. for "Query Select" widgets), and it offers both an <kbd>Execute</kbd> button on top of each editor textarea and the large <kbd>Save</kbd> button at the bottom of the editor dialog screen.

## Problem Scenario

When you use a complex query that contains single quotes then pressing the <kbd>Execute</kbd> button runs the query just fine, displaying the results at the lower end of the screen in an overlay. But when the  <kbd>Save</kbd> button is pressed, the content of each textarea is apparently HTML-encoded before saving, which immediately leads to an SQL error, e.g.

```SQL
Issue executing prepared statement: ORA-00911: invalid character
```

### Problem Analysis

The "invalid character" is apparently the ampersand ("&"). This can be seen when closing the editor dialog and reopening it again: The single quotes in the SQL have been replaced by a character sequence of "`&apos;`".

When you now save the content _again_, the same error pops up again. And when you then close and reopen the editor dialog, you'll see that the occurrences of "`&apos;`" have been replaced by "`&amp;apos;`", which confirms the assumption that HTML encoding is being performed.

## Expected Behavior

Since brute-force HTML encoding breaks the SQL code, it should not be done on SQL code.

If the SQL code is HTML-encoded for some particular reason (e.g. permissions, security concerns) the application should stop the user from saving the content to avoid prior existing code to break; the user should get appropriate and actionable feedback, instead.

**Comment by xresch** [comment] 2024-11-04 13:49
Hi @bittner,

this issue is currently caused by missing permission "Allow HTML".
However, I will check if I can disable the HTML sanitation for all Parameters, as in this case it would make sense to not have sanitation for HTML and only for Javascript.

Cheers
Reto

**Comment by xresch** [comment] 2024-11-04 16:17
Issue has been addressed in CoreFramework:
Query Select Param: https://github.com/xresch/CoreFramework/commit/e036fad0957a343981d12f9d524a4f09d9023b75
Other Params: https://github.com/xresch/CoreFramework/commit/cc09c7680265e3a342f8ed27a72c20a3416b1a2a

**Comment by xresch** [comment] 2024-12-12 07:08
ticket closed as resolved

**Closed by xresch** 2024-12-12 07:08 UTC
