### ISSUE TITLE
Drop-down box doesn't list all values

### ISSUE THREAD

**Issue by iSimsi** [xresch/EngineeredMonitoringPlatform#10] opened 2024-12-10 14:21 UTC
We have a drop-down select box labelled "Business Date" on our "FMA QualityGates" dashboards ("Add Widget" > "Advanced" > "Parameters"). The widget displays items of a combined value, which comes from an EMP parameter query. The business need behind that is that we can have several runs of "businessdate" data checks, which store their results at different times (aka database record "created").

```
| source oracle
environment=param("environment")
query=SELECT BUSINESSDATE, (CAST(CREATED AS DATE) - TO_DATE('01-JAN-70')) * 24 * 60 * 60 * 1000 AS EPOCH_CREATED FROM SCHEMA.TABLE

| set LABEL = timeformat("yyyy-MM-dd", BUSINESSDATE) + " (" + timeformat("yyyy-MM-dd HH:mm", EPOCH_CREATED) + ")"
| distinct BUSINESSDATE LABEL
| keep BUSINESSDATE LABEL
```

If we execute the query in the parameter modal we receive 5 rows which is correct, but in the drop-down select box we can only see 2 rows.

Can you help us understand if that's a technical limitation/bug or whether we simply have a logical error in the setup or the query? Is there any way to influence this behavior?

**Comment by iSimsi** [comment] 2024-12-10 16:11
[
{
"BUSINESSDATE": 1729641600000,
"LABEL": "2024-10-23 (2024-10-25 09:20)"
},
{
"BUSINESSDATE": 1732320000000,
"LABEL": "2024-11-23 (2024-11-25 14:06)"
},
{
"BUSINESSDATE": 1732320000000,
"LABEL": "2024-11-23 (2024-12-09 20:49)"
},
{
"BUSINESSDATE": 1729641600000,
"LABEL": "2024-10-23 (2024-12-09 20:58)"
},
{
"BUSINESSDATE": 1732320000000,
"LABEL": "2024-11-23 (2024-12-09 21:12)"
}
]

**Comment by xresch** [comment] 2024-12-10 16:27
Hi @iSimsi,

you have multiple select values with the same value and different labels.
In the current version of EMP this is not supported, as select options are stored in a HashMap and therefore distinct by value.

Cheers
Reto

**Comment by xresch** [comment] 2024-12-12 07:03
Hi @iSimsi,

I have checked if it make sense to change this behavior.
The issue is that select boxes will pre-select the last selected value.
This only works if the values are unique, and would lead to confusion if multiple select values are the same, as then the pre-selection would likely change the value.

Only way how I could change this behavior would be considering value and label in the pre-selection.
But this is also something I don't want to do, as this could lead again to issues with the pre-selection (e.g. if labels contain a count that changes frequently).

I will close this ticket as it will not be resolved.

**Closed** 2024-12-12 07:03 UTC

**Comment by bittner** [comment] 2024-12-12 14:40
> you have multiple select values with the same value and different labels.

IIUC, there is no way to have a combined value for a SELECT option item.

In our case, I figured, the solution would be to use the CREATED timestamp field instead of BUSINESSDATE, because that's almost certainly unique (due to that way we create the database entries). I will try that.

Unfortunately, this causes its own set of issues due to the fact that timestamp values are not particularly well supported by EMP at this time (see #3).
